### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by z16973** [mzz2017/lkl-haproxy#1]
Created symlink from /etc/systemd/system/multi-user.target.wants/lkl-haproxy.service to /etc/systemd/system/lkl-haproxy.service.
The unit files have no [Install] section. They are not meant to be enabled
using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
ioctl(TUNSETIFF): Device or resource busy

**Comment by mzz2017** [comment]
谢谢，我将进行修复

**Comment by mzz2017** [comment]
看起来是systemd的bug 
<https://github.com/coreos/bugs/issues/1512>
<https://github.com/lnykryn/systemd-rhel/pull/101>

**Comment by mzz2017** [comment]
有任何影响吗？

**Comment by z16973** [comment]
用脚本检测是处于运行状态的。但是加速效果不好，提速后只有200k，用tcp_nanqinlang版本的有1m。

**Comment by z16973** [comment]
系统是debian8    Linux pp 2.6.32-042stab120.6 #1 SMP Thu Oct 27 16:59:03 MSK 2016 x86_64 GNU/Linux

**Comment by mzz2017** [comment]
正常的，建议用fast.com或speedtest.net实测环境。

**Comment by ylx2016** [comment]
我这页报这错误 然后检测结果没有运行
webhorizon的openvz小鸡，我从debian10到debian9 再到centos7测试都不行，用2检测都是没有运行
换到nanqinlang的1.1.1就没问题
